<?php

/**
 * @file
 * Contains features_augment.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function features_augment_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the features_augment module.
    case 'help.page.features_augment':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides augmentation of features through configuration augmentation.') . '</p>';
      return $output;

    default:
  }
}
